---
galaxy_info:
  author: sam
  description: Install and configure Nginx + PHP-FPM
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies: []