---
- name: Ensure required packages are installed
  become: true
  ansible.builtin.apt:
    name:
      - nginx
      - php-fpm
      - php-cli
      - php-common
      - php-json
      - php-mbstring
      - php-xml
      - php-curl
      - logrotate
    state: present
    update_cache: true

- name: Ensure web root exists
  become: true
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Copy index.php
  become: true
  ansible.builtin.template:
    src: index.php.j2
    dest: /var/www/html/index.php
    owner: www-data
    group: www-data
    mode: "0644"

- name: Configure nginx
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart nginx

- name: Ensure nginx is running
  become: true
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Ensure PHP-FPM is running
  become: true
  ansible.builtin.service:
    name: php8.4-fpm
    state: started
    enabled: true
