name: Ansible Lint

on:
  push:
    paths:
      - 'ansible/**'
  pull_request:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Ansible and ansible-lint
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip
          pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint ansible/
